# Generated by Django 4.2.5 on 2025-04-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_questions_correct', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('fastest_quiz_completion', models.DurationField(blank=True, null=True)),
                ('slowest_quiz_completion', models.DurationField(blank=True, null=True)),
                ('weakest_subject_id', models.IntegerField(blank=True, null=True)),
                ('recommendations_received', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
